"use client"
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";
import "./custom.scss";
// import TopLoader from 'nextjs-toploader';
import { ProgressProvider } from '@bprogress/next/app';
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id='appid'
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <AntdRegistry>
          <ProgressProvider
            height="4px"
            color="#7d7cdc"
            options={{ showSpinner: false }}
            
          >
            {/* <div id='root'> */}
              {children}
            {/* </div> */}


          </ProgressProvider>
        </AntdRegistry>

      </body>
    </html>
  );
}
